### ISSUE TITLE
Figure out what's going on with "fetch failed" errors

### ISSUE THREAD

**Issue by wingated** [BYU-PCCL/aphasia-gpt-test#6]
Like this one:

Status:
Error

Error:
**Error: Error, but will not retry: TypeError: fetch failed**

Utterance:
get book me here

Known Good Completions:
Can you grab that book for me and bring it here?
This right here is my book that I just got from the library.
I need get a book to keep here.

**Comment by jordanbw1** [comment]
Error is happening in httpUtils.ts on line 50 within the last condition of the else statement. Within retryOnFailure function.

**Comment by jordanbw1** [comment]
Upload new cloud functions with better debugging info.

**Comment by jordanbw1** [comment]
Fixed issue by requiring node-fetch in HuggingFaceService.ts
